import {config} from "./config";

export default {
    bgStyle: {
        color: {
            backgroundColor: '#020D18'
        },
        image: {
            backgroundImage: `linear-gradient(rgba(2, 13, 24, 0.9), rgba(2, 13, 24, 0.9)), url("${config.ASSETS_URL}img/banner.jpg")`,
            backgroundSize: 'contain'
        }
    },

    VO: {
        'de': 'Allemand',
        'en': 'Anglais',
        'ar': 'Arabe',
        'eu': 'Basque',
        'br': 'Breton',
        'ca': 'Catalan',
        'zh-Hans': 'Chinois',
        'zh-Hant': 'Chinois_traditionnel',
        'ko': 'Coréen',
        'co': 'Corse',
        'es': 'Espagnol',
        'eo': 'Espéranto',
        'fr': 'Français',
        'el': 'Grec',
        'he': 'Hébreu',
        'hi': 'Hindi',
        'id': 'Indonésien',
        'it': 'Italien',
        'ja': 'Japonais',
        'ku': 'Kurde',
        'la': 'Latin',
        'mn': 'Mongol',
        'nl': 'Néerlandais',
        'ne': 'Népalais',
        'oc': 'Occitan',
        'ur': 'Ourdou',
        'fa': 'Persan',
        'pl': 'Polonais',
        'pt': 'Portugais',
        'ru': 'Russe',
        'ta': 'Tamoul',
        'th': 'Thaï',
        'tr': 'Turc',
        'vi': 'Vietnamien',
    },

    trad: {
        'adultery': "adultère",
        'airplane': "avion",
        'biography': "biographie",
        'horror': "horreur",
        'california': "californie",
        'christmas': "noël",
        'dc comics': "DC comics",
        'death': "mort",
        'detective': "détective",
        'space travel': "voyage spatial",
        'dream': "rêve",
        'drugs': "drogue",
        'dying and death': "mort",
        'dystopia': "dystopie",
        'escape': "évasion",
        'experiment': "expérience",
        'virtual reality': "réalité virtuelle",
        'secret identity': "identité secrète",
        'family': "famille",
        'fight': "combat",
        'friendship': "amitié",
        'future': "avenir",
        'high school': "lycée",
        'hitman': "tueur à gages",
        'holiday': "vacances",
        'hostage': "otage",
        'investigation': "enquête",
        'journalist': "journaliste",
        'lawyer': "avocat",
        'london england': "Londre",
        'magical creature': "creature magique",
        'los angeles': "Los Angeles",
        'loss of loved one': "perte d'un être cher",
        'love': "amour",
        'love of one': "être cher",
        'magic': "magique",
        'marriage': "mariage",
        'martial arts': "arts martiaux",
        'monster': "monstre",
        'murder': "meurtre",
        'musical': "musique",
        'parent child relationship': "relation parent-enfant",
        'party': "fête",
        'prostitute': "prostitué",
        'psychopath': "psychopathe",
        'rape': "viol",
        'rescue': "sauvetage",
        'revenge': "vengeance",
        'robbery': "vol",
        'post apocalyptic': "post-apocalyptique",
        'serial killer': "tueur en série",
        'sex': "sexe",
        'sibling relationship': "relation fraternelle",
        'small town': "village",
        'spy': "espion",
        'supernatural': "surnaturel",
        'teenager': "adolescent",
        'time travel': "voyage dans le temps",
        'undercover': "infiltré.",
        'wedding': "mariage",
        'wife husband relationship': "relation mari et femme",
        'witch': "sorcière",
        'world war': "guerre mondiale",
        'zombie': "zombi",
        'moon': "lune",
        'elves': 'elfe',
        'dwarf': 'nain',
        'based on comic': 'basé sur un comics',
        'super power': 'super pouvoir',
        'new york city': 'new-york',
        'manhattan new york city': 'manhattan',
        'world war ii': 'seconde guerre mondiale',
        'world war i': 'premiere guerre mondiale',
        'dream world': 'monde imaginaire',
        'based on novel or book':"adaptés d'un roman"
    },
}
